### Post request
POST http://localhost:8081/users
Content-Type: application/json

{
  "name": "Lebron",
  "email": "lebron-user-test@james.com"
}

###



### Post request
POST http://host_part_name.eu-central-1.elasticbeanstalk.com//users
Content-Type: application/json

{
  "name": "New",
  "email": "new-user-test@james.com"
}

###
